[package]
name = "image_dedup"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.23"
img_hash = "3.2"
anyhow = "1.0"
walkdir = "2.3"
async-trait = "0.1"
tokio = { version = "1.32", features = ["full"] }
base64 = "0.22"
hex = "0.4"

[dev-dependencies]
tempfile = "3.8"
